name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci 
      - run: ls -la
      - run: npm run
      - run: npm test > test-results.txt
      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: test-results
          path: artifacts
      - run: cat artifacts/test-results.txt
      - run: |
          npm install
          npm start &
